gpn:
  gamehunter:
    url: http://lowcygier.pl
  scheduling:
    scrapping:
      cron: "*/2 * * * * *"
    publishing:
      cron: "*/2 * * * * *"
  queue:
    name: posts

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
      username: root
      password: example
      authentication-database: admin
      auto-index-creation: true
      uuid-representation: standard
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test

