gpn:
  gamehunter:
    url: http://lowcygier.pl
  scheduling:
    cron: "0 * * * * *"
  queue:
    name: posts

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
      username: root
      password: example
      authentication-database: admin
      auto-index-creation: true
