gpn:
  gamehunter:
    url: http://lowcygier.pl
  scheduling:
    scrapping:
      cron: "*/2 * * * * *"
    publishing:
      cron: "*/2 * * * * *"
  queue:
    name: posts

mongodb:
  replicaSet: replicaset

spring:
  application:
    name: pn-site-scrapper
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
      username: root
      password: example
      authentication-database: admin
      auto-index-creation: true
      uuid-representation: standard
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

