image:
  repository: scrapper-app
  tag: latest

fullNameOverride: "pn-site-scrapper"

env:
  gpn.gamehunter.url: "http://lowcygier.pl"
  gpn.scheduling.scrapping.cron: '*/2 * * * * *'
  gpn.scheduling.publishing.cron: '*/2 * * * * *'
  gpn.queue.name: posts
  mongodb.replicaSet: rs0
  spring.data.mongodb.host: pn-site-scrapper-headless
  spring.data.mongodb.port: 27017
  spring.data.mongodb.database: posts
  spring.data.mongodb.username: root
  spring.data.mongodb.password: password
  spring.data.mongodb.authentication-database: admin
  spring.data.mongodb.auto-index-creation: true
  spring.data.mongodb.uuid-representation: standard
  spring.rabbitmq.host: rabbitmq-posts
  spring.rabbitmq.port: 5672
  spring.rabbitmq.username: user
  spring.rabbitmq.password: password

nosqldb:
  enabled: true

mongodb:
  image:
    tag: "5.0.6-debian-10-r6"
  auth: 
    rootPassword: password
    usernames: [user]
    passwords: [password]
    databases: [admin]
  nameOverride: pn-site-scrapper
  architecture: replicaset
  replicaSetName: rs0
  replicaCount: 2
  # arbiter:
  #   enabled: false

