gpn:
  queue:
    name: 'posts'
  user-service:
    url: http://localhost:8080
  subscription-service:
    url: http://localhost:8081
  matching-service:
    mongodb:
      collectionName: "user-offer-matches"
    publishing:
      cron: "*/1 * * * * *"
      queue:
        name: "notifications"
spring:
  data:
    mongodb:
      database: posts
      username: root
      password: password
      authentication-database: admin
      auto-index-creation: true