spring:
  application:
    name: pn-subscription-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/promotion-notifier
  elasticsearch:
    rest:
      uris: localhost:9200
  main:
    banner-mode: log

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  config: classpath:logback.xml