version: '3.7'

services:
  mongo:
    image: bitnami/mongodb:4.4.12
    restart: always
    environment:
      MONGODB_ROOT_PASSWORD: example
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicaset
      MONGODB_DATABASE: posts
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
  rabitmq:
    image: bitnami/rabbitmq:3.8.18
    restart: always
    environment:
      RABBITMQ_USERNAME: test
      RABBITMQ_PASSWORD: test
    ports:
      - "5672:5672"
      - "15672:15672"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"