gpn:
  scheduling:
    scrapping:
      cron: "*/1 * * * * *"
    publishing:
      cron: "*/1 * * * * *"
  queue:
    name: posts

spring:
  data:
    mongodb:
      database: posts
      username: root
      password: password
      authentication-database: admin
      auto-index-creation: true
  rabbitmq:
    username: test
    password: test