spring:
  application:
    name: pn-user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users
    username: test
    password: test
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create-only
  jackson:
    serialization:
      write_dates_as_timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  config: classpath:logback.xml
