spring:
  mail:
    default-encoding: UTF-8
    host: localhost
    username: promotionnotificationsapp@gmail.com
    password: testApp2021
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: true
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test

gpn:
  queueName : new-offers-matches