spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users
    username: test
    password: test
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create
