spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: promotionnotificationsapp@gmail.com
    password: testApp2021
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: true
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test

gpn:
  rabbitmq :
    exchange : new-offers-exchange
    queue : new-offers-matches
    dead-letter-exchange : new-offers-exchange-dead-letter
    dead-letter-queue : new-offers-matches-dead-letter