spring:
  application:
    name: pn-email-service
  main:
    banner-mode: log
  mail:
    default-encoding: UTF-8
    host: localhost
    username: test
    password: test
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: true
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test

gpn:
  rabbitmq :
    exchange : new-offers-exchange
    queue : new-offers-matches
    dead-letter-exchange : new-offers-exchange-dead-letter
    dead-letter-queue : new-offers-matches-dead-letter

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  config: classpath:logback.xml