apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-app.fullname" . }}
  namespace: default
  labels: 
    {{- include "backend-app.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.env }}
  {{ $k | replace "." "_" | replace "-" "" | upper }}: {{ $v | quote }}
{{- end }}