name: game-promotion-notifier-backend-ci
on: [push]
jobs:
  build:
    environment: DEFAULT
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./game-promotion-notifier-backend
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./game-promotion-notifier-backend
    - name: Run integration tests
      run: ./gradlew integTest
      working-directory: ./game-promotion-notifier-backend
