name: promotion-notifier-backend-ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./promotion-notifier-backend
    - name: Build with Gradle
      run: ./gradlew build -i
      working-directory: ./promotion-notifier-backend

    - name: Run integration tests
      run: ./gradlew integTest -i
      working-directory: ./promotion-notifier-backend
    - name: Generate coverage report
      run: ./gradlew codeCoverageReport
      working-directory: ./promotion-notifier-backend
    - name: Upload coverage report
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}
      working-directory: ./promotion-notifier-backend
